apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: shared-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: gcr.io/ebram-377521/jenkins

          ports:
            - name: httpport
              containerPort: 8080

          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home  
      volumes:
        - name: jenkins-data
          emptyDir: {}
        

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: shared-services
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: jenkins