apiVersion: v1                           
kind: ConfigMap
metadata:
  name: example-configmap
data:
   ENVIRONMENT: DEV
   HOST: localhost
   PORT: "8000"
   REDIS_DB: "0"
   REDIS_HOST: redis
   REDIS_PORT: "6379"