apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
#  namespace: shared-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus-container
          image: gcr.io/ebram-377521/nexus:v3
          resources:
            limits:
              memory: "200Mi"
              cpu: "200m"
            requests:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
      volumes:
        - name: nexus-data
          emptyDir: {}
        

---
apiVersion: v1
kind: Service
metadata:
  name: nexus
#  namespace: shared-services
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: nexus


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nexus
# #  namespace: shared-services
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: nexus
#   template:
#     metadata:
#       labels:
#         app: nexus
#     spec:
#       containers:
#         - name: nexus-container
#           image: gcr.io/ebram-377521/nexus:v3
#           resources:
#             limits:
#               memory: "2Gi"
#               cpu: "1000m"
#             requests:
#               memory: "1Gi"
#               cpu: "250m"
#           ports:
#             - containerPort: 8081
#           volumeMounts:
#             - name: nexus-data
#               mountPath: /nexus-data
#       volumes:
#         - name: nexus-data
#           emptyDir: {}
        

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nexus
# #  namespace: shared-services
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 8081
#       targetPort: 8081
#   selector:
#     app: nexus